### ISSUE TITLE
create_h5_nusc.py then error came out

### ISSUE THREAD

**Issue by KYYOnull** [roggirg/AutoBots#26]
i use the mini data of nusecene and orgnize the file dir  as you showed in readme.. but it errored like this:

Traceback (most recent call last):
  File ".\datasets\nuscenes\create_h5_nusc.py", line 76, in <module>
    for i, data in enumerate(nuScenes):
  File "D:\zzp\model\AutoBots\datasets\nuscenes\raw_dataset.py", line 249, in __getitem__
    annotation = self._helper.get_sample_annotation(instance_token, sample_token)
  File "C:\Users\gcn\anaconda3\envs\autobots\lib\site-packages\nuscenes\prediction\helper.py", line 165, in get_sample_annotation
    return self.data.get('sample_annotation', self.inst_sample_to_ann[(sample_token, instance_token)])
KeyError: ('faf2ea71b30941329a3c3f3866cec714', '4d87aaf2d82549969f1550607ef46a63')

**Comment by roggirg** [comment]
Hi @KYYOnull ,

It has been a few years since I have looked at Nuscenes, it is very likely they have updated the devkit since then. I would suggest looking at their instructions here: https://github.com/nutonomy/nuscenes-devkit

Let me know if that helps.

**Comment by KYYOnull** [comment]
i'm greenhand the nusecene it's too hard to me to make a preprocessed data to feed in network.. so i'm not sure where it went wrong.. do you think the mini dataset about 3.88G on officail website can fit the h5making code well, as well&nbsp; as the whole nusecene dataset over 300G.. i will try more nusecene kits versions if it won't make out the preprocessed data i'll quit..




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "roggirg/AutoBots"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 晚上10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [roggirg/AutoBots] create_h5_nusc.py then error came out (Issue #26)





 
Hi @KYYOnull ,
 
It has been a few years since I have looked at Nuscenes, it is very likely they have updated the devkit since then. I would suggest looking at their instructions here: https://github.com/nutonomy/nuscenes-devkit
 
Let me know if that helps.
